title: Welcome Folks
author: Vamshi Duddu
email: vamshiduddu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey There i like to Explore new technologies and learn them
# social links
twitter_username:vamshiduddu
github_username:  vamrex

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-leap-day
